title: Dock 18
short_title: Dock 18
description: Dock 18
baseurl:
permalink: "/:path/"
cloudinary_url: "https://res.cloudinary.com/dock18/image/upload"
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_events"
    values:
      layout: event
  - scope:
      path: "_products"
    values:
      layout: product
  - scope:
      path: "_forms"
    values:
      layout: form
collections:
  banners:
    output: false
  products:
    output: true
    permalink: /:name/
  textbanner:
    output: false
  fullsizetextbanner:
    output: false
  events:
    output: true
    permalink: /:name/
  stores:
    output: false
  creation:
    output: false
  instagram:
    output: false
  forms:
    output: true
jekyll-archives:
  enabled: all
  layout: "archive"
exclude:
  - "package.json"
  - "webpack.config.js"
  - "js/"
  - "sass/"
  - "font-awesome.config.js"
  - "node_modules/**/*"
  - ".idea/**/*"
  - "Gemfile"
  - "Gemfile.lock"
  - "*.otf"
url: "https://dock-18.de"
plugins:
  - jekyll-menus
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-seo-tag

jekyll_analytics:
  GoogleAnalytics:         # Add, if you want to track with Google Analytics
    id: UA-126695047-1     # Required - replace with your tracking id
    anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking