---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  label: Pages
  create: all
  path: ''
  match: "*.md"
  exclude: "*README.md"
  new_doc_ext: md
  templates:
  - landing-page
  - html-content
  - home-page
- type: document
  label: Banners
  directory: '_banners/'
- type: document
  label: Events
  directory: '_events/'
- type: document
  label: Products
  directory: '_products/'
- type: document
  label: Stories
  directory: '_stories/'
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
