---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Pages
  create: all
  match: "*.md"
  exclude: "*README.md"
  new_doc_ext: md
  templates:
  - landing-page
  - html-content
  - home-page
- type: directory
  label: Banners
  path: _banners
  match: "*.yml"
  new_doc_ext: ".yml"
  create: all
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
