---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - html-content
  - home-page
- type: document
  label: Banners
  templates:
  - landing-page
  - html-content
  - home-page
- type: document
  label: Events
  templates:
  - landing-page
  - html-content
  - home-page
- type: document
  label: Products
  templates:
  - landing-page
  - html-content
  - home-page
- type: document
  label: Stories
  templates:
  - landing-page
  - html-content
  - home-page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
